### ISSUE TITLE
Buffer out of DiskSpace?

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/php-vips#54]
I am trying this, and it works about 90% of the time.

```php
 $image = Image::newFromBuffer($sourceBlob);
 $resultBlob = $image->dzsave_buffer(
             [
                 'basename' => $event->getMessage()->getCachename(),
                 'suffix' => '.jpg',
                 'depth' => 'onetile',
                 'layout' => 'zoomify',
                 'container' => 'zip',
                 'properties' => false,
                 'compression' => 9,
                 'strip' => true
 
             ]
         );
```

However, if the source file is large, then I end up with:
```
wbuffer_write: write failed
unix error: No space left on device
[object] (Jcupitt\Vips\Exception(code: 0): wbuffer_write: write failed unix error: No space left on device at /var/task/project/vendor/jcupitt/vips/src/Image.php:664)
[stacktrace]
#0 /var/task/project/vendor/jcupitt/vips/src/Image.php(685): Jcupitt\Vips\Image::errorVips()
#1 /var/task/project/vendor/jcupitt/vips/src/Image.php(1052): Jcupitt\Vips\Image::errorIsArray(-1)
#2 /var/task/project/vendor/jcupitt/vips/src/Image.php(1130): Jcupitt\Vips\Image::callBase('dzsave_buffer', Object(Jcupitt\Vips\Image), Array)
```

I was really under the impression that when I worked with buffers **nothing** would be written to the disk. Is there any way to ensure that is true, that everything happens in memory?

**Comment by jcupitt** [comment]
Huh, strange, yes, I'd think it shouldn't touch disc as well. I'll have a look.

**Comment by jcupitt** [comment]
Oh, of course if the image is large and it doesn't support random access, it'll need to unpack it to a temporary area first for processing. If this temporary object is large, it'll use disc.

You need to tell `newFromBuffer` that you only need sequential access. Try:

```php
 $image = Image::newFromBuffer($sourceBlob, ['sequential' => true]);
```

erm or is it TRUE? I've forgotten :-(

**Comment by bubba-h57** [comment]
I tried:

```php
<?php
/** 
 * $sourceBlob is a 140.21 MB PNG slurped in via 
 * /tmp is a 524.29MB tmpfs
 */

use Jcupitt\Vips\Image;

require_once __DIR__ . '/vendor/autoload.php';

$scale = 0.21333333333333;

print(shell_exec('df -h'));

$sourceBlob = file_get_contents('140.21MB.png');
print("\nSlurped it up.\n");
printf("/tmp free space: %s\n\n", disk_free_space('/tmp'));

$image = Image::newFromBuffer($sourceBlob, '', ['sequential' => true]);
print("Loaded into VIPS Image from Buffer.\n");
printf("/tmp free space: %s\n\n", disk_free_space('/tmp'));

// This Executes
$image = $image->resize($scale);
print("Resized the Image to scale.\n");
printf("/tmp free space: %s\n\n", disk_free_space('/tmp'));

// This Throws the error.
$resultBlob = $image->dzsave_buffer(
    [
        'basename' => 'slurpee',
        'suffix' => '.jpg',
        'depth' => 'onetile',
        'layout' => 'zoomify',
        'container' => 'zip',
        'properties' => false,
        'compression' => 9,
        'strip' => true

    ]
);

```

The output was:

```
(Wed Sep-9 1:44:57am)-(CPU 0.5%:0:Net 1)-(root:/var/task)-(134M:27)
> php -d memory_limit=2.5G test.php 
Filesystem      Size  Used Avail Use% Mounted on
overlay          63G   27G   34G  44% /
tmpfs          1000M     0 1000M   0% /dev
tmpfs          1000M     0 1000M   0% /sys/fs/cgroup
osxfs           597G  427G  170G  72% /var/task
/dev/vda1        63G   27G   34G  44% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           500M     0  500M   0% /tmp

Slurped it up.
/tmp free space: 524288000

Loaded into VIPS Image from Buffer.
/tmp free space: 524288000

Resized the Image to scale.
/tmp free space: 524288000


(banana:1414): VIPS-WARNING **: error in tile 0 x 0

(banana:1414): VIPS-WARNING **: error in tile 0 x 0

(banana:1414): VIPS-WARNING **: error in tile 0 x 10

(banana:1414): VIPS-WARNING **: error in tile 0 x 20

(banana:1414): VIPS-WARNING **: error in tile 0 x 30

(banana:1414): VIPS-WARNING **: error in tile 0 x 40

(banana:1414): VIPS-WARNING **: error in tile 0 x 50

(banana:1414): VIPS-WARNING **: error in tile 0 x 60

(banana:1414): VIPS-WARNING **: error in tile 0 x 70

(banana:1414): VIPS-WARNING **: error in tile 0 x 80

(banana:1414): VIPS-WARNING **: error in tile 0 x 90

(banana:1414): VIPS-WARNING **: error in tile 0 x 100

(banana:1414): VIPS-WARNING **: error in tile 0 x 110

(banana:1414): VIPS-WARNING **: error in tile 0 x 120
PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: wbuffer_write: write failed
unix error: No space left on device
 in /var/task/project/vendor/jcupitt/vips/src/Image.php:664
Stack trace:
#0 /var/task/project/vendor/jcupitt/vips/src/Image.php(685): Jcupitt\Vips\Image::errorVips()
#1 /var/task/project/vendor/jcupitt/vips/src/Image.php(1052): Jcupitt\Vips\Image::errorIsArray(-1)
#2 /var/task/project/vendor/jcupitt/vips/src/Image.php(1130): Jcupitt\Vips\Image::callBase('dzsave_buffer', Object(Jcupitt\Vips\Image), Array)
#3 /var/task/project/test.php(27): Jcupitt\Vips\Image->__call('dzsave_buffer', Array)
#4 {main}
  thrown in /var/task/project/vendor/jcupitt/vips/src/Image.php on line 664
(ERROR)-(Exit Code 255)-(Unknown error code)

```

**Comment by kleisauke** [comment]
Try this:
```php
$image = Image::newFromBuffer($sourceBlob, '', ['access' => 'sequential']);
```

**Comment by jcupitt** [comment]
Oh, duh, thank you Kleis, of course it's `access`. It was late :( 

I tried the test program and it seems to work fine for me with a 100mb PNG, and does not touch disc.

**Comment by jcupitt** [comment]
Side-note: you can use `writeToBuffer` instead of `dzsave`, it's perhaps a little neater. The `.dz` suffix is linked to deep zoom save. 

```
$resultBlob = $image->writeToBuffer(".dz", [
        'basename' => 'slurpee',
        'suffix' => '.jpg',
        'depth' => 'onetile',
        'layout' => 'zoomify',
        'container' => 'zip',
        'properties' => false,
        'compression' => 9,
        'strip' => true
]);
```

**Comment by bubba-h57** [comment]
I will try that this morning. Here is [a dropbox link to the 140.21MB.png](https://www.dropbox.com/s/g98054khrh81pgp/140.21MB.png?dl=0), the file I am testing with.

**Comment by bubba-h57** [comment]
No difference using the `writeToBuffer()` method.

**Comment by bubba-h57** [comment]
Oh oh oh! `['access' => 'sequential']` appears to have done it!

**Comment by bubba-h57** [comment]
Yes, my test suite is no longer choking on this. Thanks, everyone, I am closing this ticket.
